recorder:
  ros__parameters:
    use_sim_time: false
    record:
      all_topics: true
      all_services: true
      all_actions: true
      is_discovery_disabled: false
      exclude_topic_types: ["sensor_msgs/msg/Image"]
      rmw_serialization_format: "cdr"
      topic_polling_interval:
        sec: 0
        nsec: 10000000
      compression_mode: "file"
      compression_format: "zstd"
      compression_queue_size: 10
      compression_threads: 2
      compression_threads_priority: -1
      qos_profile_overrides_path: "/home/jerome/gh_ws/src/ros2_data_logger/config/recorder_qos_profile.yaml"
      include_hidden_topics: true
      include_unpublished_topics: true
      ignore_leaf_topics: false
      start_paused: false
      disable_keyboard_controls: true
      statistics_max_publishing_rate: 0.5

    storage:
      storage_id: "mcap"
      max_bagfile_size: 5368709120  # 5 GB
      storage_preset_profile: "none"
      snapshot_mode: false
